// Canonical server build script.
// Run via: node scripts/server-build.js
// This is the only step that should produce server_dist — never edit
// server_dist/templates directly. The Start Backend workflow and the
// deployment build both invoke this script so server_dist always mirrors
// the source files in server/.
import { execSync } from 'child_process';
import { cpSync, existsSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');

console.log('Building server...');
execSync('npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=server_dist', {
  cwd: rootDir,
  stdio: 'inherit'
});

console.log('Copying templates...');
const templatesSource = join(rootDir, 'server', 'templates');
const templatesDest = join(rootDir, 'server_dist', 'templates');
if (existsSync(templatesSource)) {
  cpSync(templatesSource, templatesDest, { recursive: true });
  // Stamp each HTML file with a generated-file warning so it is obvious
  // that server_dist/templates must not be edited by hand.
  const banner =
    '<!-- AUTO-GENERATED — do not edit this file directly.\n' +
    '     Source: server/templates/<filename>  →  regenerated by scripts/server-build.js\n' +
    '     Edit the source file; the dist copy is overwritten on every build. -->\n';
  for (const file of readdirSync(templatesDest)) {
    if (file.endsWith('.html')) {
      const filePath = join(templatesDest, file);
      const original = readFileSync(filePath, 'utf-8');
      writeFileSync(filePath, banner + original, 'utf-8');
    }
  }
  console.log('Templates copied successfully');
}

console.log('Copying public folder...');
const publicSource = join(rootDir, 'server', 'public');
const publicDest = join(rootDir, 'server_dist', 'public');
if (existsSync(publicSource)) {
  cpSync(publicSource, publicDest, { recursive: true });
  console.log('Public folder copied successfully');
}

console.log('Server build complete!');
