// AUTO-GENERATED by build script - do not edit manually
// In development, falls back to process.env values
export const GENERATED_ENV = {
  REVENUECAT_IOS_KEY: "",
  REVENUECAT_ANDROID_KEY: "",
} as const;
